import { GoogleGenAI, Modality } from "@google/genai";

/**
 * 初始化 GoogleGenAI 实例。
 * @param apiKey Google AI Studio 的 API 密钥。此参数必须是字符串，且不能为 undefined。
 * @returns GoogleGenAI 实例。
 */
const getAi = (apiKey: string) => {
    // 这里不再需要检查 apiKey 是否为 undefined，因为 TypeScript 已经保证了它是 string。
    // 如果在调用此函数之前未确保 apiKey 是 string，TypeScript 会在编译时报错。
    return new GoogleGenAI({ apiKey });
}

/**
 * 根据电影场景描述创建详细的图像生成提示。
 * @param sceneDescription 电影场景的描述。
 * @param apiKey Google AI Studio 的 API 密钥。此参数必须是字符串。
 * @returns 增强后的图像生成提示字符串。
 * @throws Error 如果图像生成失败。
 */
export const createEnhancedImagePrompt = async (sceneDescription: string, apiKey: string): Promise<string> => {
    const ai = getAi(apiKey); // apiKey 已经被保证是 string
    const prompt = `Translate the following movie scene description into a detailed, visually rich English prompt for an image generation model. The prompt should be a single paragraph. Add cinematic keywords like "cinematic lighting", "epic scale", "photorealistic", "4k", "high detail". Scene: "${sceneDescription}"`;

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
    });

    return response.text;
};

/**
 * 根据给定的提示生成图像。
 * @param prompt 用于生成图像的详细提示。
 * @param apiKey Google AI Studio 的 API 密钥。此参数必须是字符串。
 * @returns 生成图像的 Base64 编码数据字符串。
 * @throws Error 如果图像生成失败。
 */
export const generateImageFromPrompt = async (prompt: string, apiKey: string): Promise<string> => {
    const ai = getAi(apiKey); // apiKey 已经被保证是 string
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [{ text: prompt }],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }

    throw new Error("No image was generated by the API for this scene.");
};
