import { GoogleGenAI, Modality } from "@google/genai";

const getAi = (apiKey: string) => {
    if (!apiKey) {
        throw new Error("API_KEY is not provided.");
    }
    return new GoogleGenAI({ apiKey });
}

export const createEnhancedImagePrompt = async (sceneDescription: string, apiKey: string): Promise<string> => {
    const ai = getAi(apiKey);
    const prompt = `Translate the following movie scene description into a detailed, visually rich English prompt for an image generation model. The prompt should be a single paragraph. Add cinematic keywords like "cinematic lighting", "epic scale", "photorealistic", "4k", "high detail". Scene: "${sceneDescription}"`;

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
    });

    return response.text;
};

export const generateImageFromPrompt = async (prompt: string, apiKey: string): Promise<string> => {
    const ai = getAi(apiKey);
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [{ text: prompt }],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }

    throw new Error("No image was generated by the API for this scene.");
};